GENRESOVERRIDE = {
    "18/19":"",
    "69position":"69",
    "acrylicplug":"Acrylic Plug",
    "action":"",
    "adult":"",
    "adult-gaybb":"",
    "airtight":"Airtight",
    "amateur":"Amateur",
    "anal":"Anal",
    "analfingering":"Fingering",
    "analfisting":"Fisting",
    "analstretching":"Anal Stretching",
    "arabguy":"Arab",
    "arabian":"Arab",
    "arabianmigrants":"Arab",
    "asian":"Asian",
    "asshook":"Ass Hook",
    "assplay/fingering":"Fingering",
    "assrimming":"Rimming",
    "asstomouth":"Ass To Mouth",
    "athletic":"Athletic",
    "backroomsanddonjons":"Backrooms And Donjons",
    "ballgag":"Ball Gag",
    "bareback":"Bareback",
    "bdsm":"BDSM",
    "bear":"Bear",
    "beautifulmen":"",
    "bedroom":"",
    "bellypunching":"Belly Punching",
    "bigass":"Big Ass",
    "bigcock":"Hung",
    "bigdick":"Hung",
    "bigdicks":"Hung",
    "bigmuscleguys":"Muscle",
    "bigtoy":"Big Toy",
    "bisexuals":"Bisexuals",
    "bitgag":"Bit Gag",
    "bizarre":"Bizarre",
    "black":"Black",
    "blackguys":"Black",
    "blackhair":"Black Hair",
    "blackmen":"Black",
    "blindedeyes":"Blindfold",
    "blindfold":"Blindfold",
    "blond":"Blonde",
    "blonde":"Blonde",
    "blowjobs":"Blow Jobs",
    "blowjob":"Blow Jobs",
    "blue-collar":"Blue-Collar",
    "bodybuilder":"Body Builders",
    "bodywriting":"Body Writing",
    "bondage":"Bondage",
    "bonus":"",
    "boot":"Boots",
    "bootworship":"Boots",
    "bottom":"",
    "brunet":"Brunette",
    "brunette":"Brunette",
    "brutalpunishment":"Brutal Punishment",
    "bukkake":"Bukkake",
    "businessattire":"Business Attire",
    "buttplug":"Buttplug",
    "cage":"Cage",
    "caning":"Caning",
    "cattleprod":"Cattle Prod",
    "cbt":"CBT",
    "cellars":"Cellars",
    "chains":"Chains",
    "chastityplay":"Chastity Play",
    "choking":"Choking",
    "christmas":"",
    "circumcised":"Circumcised",
    "clothespins":"Clothespins",
    "cloverclamps":"Clover Clamps",
    "cockworship":"Cock Worship",
    "collar":"Blue-Collar",
    "condom-free":"Bareback",
    "cop":"Cop",
    "corporalpunishment":"Corporal Punishment",
    "cosplay":"Cosplay",
    "couple":"Couple",
    "creampie":"Creampie",
    "creeping":"Creeping",
    "crop":"Crop",
    "crotchrope":"Crotch Rope",
    "crying":"Crying",
    "cuminmouth":"Cum In Mouth",
    "cuminside":"Cum Inside",
    "cumonass":"Cum on Ass",
    "cumsmearing":"Cum Smearing",
    "cumswallowing":"Cum Swallowing",
    "cumshot":"Cumshot",
    "daddy":"Daddy",
    "daddy&bear":"Daddy",
    "daddyguys":"Daddy",
    "deepthroat":"Deepthroat",
    "deepthroat":"Deepthroat",
    "deprivation":"Deprivation",
    "destruction":"Destruction",
    "dildo":"Dildo",
    "dildosandsextoys":"Dildo",
    "discipline":"Discipline",
    "doctor":"Doctor",
    "dogtraining":"Dog Training",
    "doggystyle":"Doggystyle",
    "domination":"Domination",
    "doubleanal":"Double Penetration",
    "doublepenetration":"Double Penetration",
    "dungeon":"Dungeon",
    "dunking":"Dunking",
    "edging":"Edging",
    "electricdildo":"Electric Dildo",
    "electricalplay":"Electro",
    "electro":"Electro",
    "electroclamp":"Electro",
    "electroplug":"Electro Plug",
    "emspads":"Electro",
    "enema":"Enema",
    "euro":"Euro Guys",
    "euroguys":"Euro Guys",
    "exhibandvoyeurs":"Exhib And Voyeurs",
    "extremetorment":"Punishment",
    "facefucking":"Facefucking",
    "facial":"Facial",
    "facialejac":"Facial",
    "fearplay":"Fear Play",
    "feet":"Feet",
    "feetworship":"Feet",
    "fetish":"",
    "fingersucking":"Finger Sucking",
    "fistfucking":"Fisting",
    "fisting":"Fisting",
    "flipflopfuck":"Flip-Flop",
    "flip-flop":"Flip-Flop",
    "flogging":"Flogging",
    "folsomstreet":"",
    "foot":"Feet",
    "footplay/feet":"Feet",
    "foottorment":"Feet Torment",
    "foreskin":"Foresking",
    "fucking":"",
    "fucksaw":"Fuck saw",
    "gag":"Gag",
    "gangbang":"Gang Bang",
    "gangbanggroupsex":"Gang Bang",
    "gangbang":"Gang Bang",
    "gaping":"Gaping",
    "garden":"Garden",
    "gay":"",
    "gaybitch":"",
    "gayorgy":"Orgy",
    "gaypigs,sexindirt":"Sex In Dirt",
    "gaysexinpublic":"Public Sex",
    "gaysuperhero":"Superhero",
    "gaybeeg":"",
    "gloryhole":"Glory Holes",
    "gloryholes":"Glory Holes",
    "gloryholes":"Glory Holes",
    "gloves":"Gloves",
    "group":"Gang Bang",
    "groupsex":"Gang Bang",
    "guys18/25yo":"Guys 18/25 yo",
    "guys25/30yo":"Guys 25/30 yo",
    "guys30yo&more":"Guys 30 yo & more",
    "hairpulling":"Hair Pulling",
    "hairy":"Hairy Guys",
    "hairyguys":"Hairy Guys",
    "hairymen":"Hairy Guys",
    "halloween":"",
    "handgagging":"Hand Gagging",
    "handjob":"Hand Job",
    "handjob":"Hand Job",
    "handler":"Handler",
    "hardsex":"Hard Sex",
    "hardcore":"Hardcore",
    "harness":"Harness",
    "highdefinition":"",
    "highdefinitiongayporn":"",
    "hitachi":"",
    "holidays":"",
    "hood":"Hoods",
    "hoods":"Hoods",
    "hotwax":"Hot Wax",
    "humiliation":"Humiliation",
    "hunk":"Hunk",
    "intergenerational":"Intergenerational",
    "interracial":"Interracial",
    "interracialsex":"Interracial",
    "jock":"Jocks",
    "jocks":"Jocks",
    "jockstrap":"Jockstraps",
    "jockstraps":"Jockstraps",
    "kinky":"Kinky",
    "latex":"Latex",
    "latingayporn":"Latino Guys",
    "latino":"Latino Guys",
    "latinoguys":"Latino Guys",
    "latinx":"Latino Guys",
    "leather":"Leather",
    "leatherbelt":"Leather Belt",
    "leathercuffs":"Leather Cuffs",
    "leathergloves":"Leather Gloves",
    "liftandcarry":"Lift And Carry",
    "livingroom":"",
    "locker-room":"Locker-Room",
    "machinedildo":"Machine Dildo",
    "machomen":"Macho Men",
    "malehandler":"Male Handler",
    "malesub":"Male Sub",
    "mask":"Mask",
    "massage":"Massage",
    "master":"Master",
    "masturbation":"Masturbation",
    "max":"",
    "medicalfetish":"Medical",
    "metalbondage":"Bondage - Metal",
    "metalplug":"Metal Plug",
    "military":"Military",
    "mixed":"Mixed Race",
    "mouthspreader":"Mouth Spreader",
    "muscle":"Muscled Men",
    "muscleworship":"Muscle Worship",
    "muscledmen":"Muscled Men",
    "muscles":"Muscled Men",
    "muscular":"Muscled Men",
    "nippleclamps":"Nipple Clamps",
    "nippletorment":"Nipple Torment",
    "nurse":"Nurse",
    "odors":"Odors",
    "office&costumes":"Office & Costumes",
    "officesex":"Office Sex",
    "older/younger":"Older/Younger",
    "oneontwo":"One On Two",
    "oralsex":"Oral Sex",
    "orgasmdenial":"Orgasm Denial",
    "orgies":"Orgy",
    "orgy":"Orgy",
    "otcsocks":"OTC Socks",
    "otherhaircolor":"",
    "outdoorsex":"Outdoor Sex",
    "outdoors":"Outdoor Sex",
    "paddle":"Paddle",
    "pain":"Pain",
    "painslut":"Pain",
    "petplay":"Pet Play",
    "piercednipples":"Piercings",
    "piercings":"Piercings",
    "piggysex":"Piggy Sex",
    "pigs":"Pigs",
    "piss":"Piss Play",
    "pissplay":"Piss Play",
    "pissing":"Piss Play",
    "pov":"",
    "predicamentbondage":"Predicament Bondage",
    "prolapse":"Prolapse",
    "prostatestimulation":"Prostate Stimulation",
    "publictoilets":"Public toilets",
    "punching":"Punching",
    "punishment":"Punishment",
    "puppyplay":"Puppy Play",
    "rack":"Rack",
    "rascalsandthugs":"Rascals And Thugs",
    "redhead":"Redhead",
    "residentcums":"Resident Cums",
    "rimming":"Rimming",
    "roleplay":"Role Play",
    "rope/bondage":"Bondage - Rope",
    "ropebondage":"Bondage - Rope",
    "rough":"Rough Sex",
    "roughgaysex":"Rough Sex",
    "roughsex":"Rough Sex",
    "sadism":"Sadism",
    "safesex":"Safe Sex",
    "shackle":"Shackle",
    "shaped":"Shaped",
    "shavethehair":"Shave The Hair",
    "shaved":"Shaved",
    "sheersocks":"Sheer Socks",
    "singletail":"Single Tail",
    "skins":"Skins",
    "slapping":"Slapping",
    "slave":"Slaves",
    "slaves":"Slaves",
    "slim":"Slim",
    "sling":"Sling",
    "slingfuckers":"Sling",
    "smoking":"Smoking",
    "smooth":"Smooth",
    "sneakers":"Sneakers",
    "socksandsneakers":"Socks And Sneakers",
    "softsex":"Soft Sex",
    "solo":"Solo",
    "solomale":"Solo",
    "southern":"",
    "spanking":"Spanking",
    "speculum":"Speculum",
    "spidergag":"Spider Gag",
    "spitinmouth":"Spit in Mouth",
    "spitroast":"Spit Roast",
    "spitting":"Spitting",
    "stocks":"Stocks",
    "str8":"Straight Men",
    "str8bait":"Straight Men",
    "straight":"Straight Men",
    "straightmen":"Straight Men",
    "straightstud":"Straight Men",
    "straitjacket":"Straitjacket",
    "stud":"Stud",
    "sub":"Sub",
    "submission":"Submission",
    "suitsex":"Suit Sex",
    "suspension":"Suspension",
    "swallow":"Swallow",
    "switch":"Switch",
    "sybian":"",
    "tagteam":"Tag Team",
    "takedown":"Takedown",
    "taser":"Taser",
    "tattoo":"Tattoos",
    "tattoos":"Tattoos",
    "tensunit":"",
    "terrass":"",
    "thanksgiving":"",
    "thechair":"Chair",
    "thecross":"Cross",
    "thepit":"Pit",
    "thewall":"Wall",
    "thewaterchamber":"",
    "threesome":"Threesome",
    "threeway":"Threeway Sex",
    "threewaysex":"Threeway Sex",
    "tickling":"Tickling",
    "toned":"toned",
    "top":"",
    "toys":"Toys",
    "tuxedo":"Tuxedo",
    "twink":"Twinks",
    "twinks":"Twinks",
    "twoonone":"Two on One",
    "uncircumcised":"Uncut Guys",
    "uncut":"Uncut Guys",
    "uncutguys":"Uncut Guys",
    "uniform":"Uniforms",
    "uniforms,military":"Uniforms",
    "unshaved":"Unshaved",
    "uro":"",
    "verbal":"Verbal",
    "versatile":"",
    "vibrator":"Vibrator",
    "violetwand":"Violet Wand",
    "virgin":"Virgin",
    "voyeur":"Voyeur",
    "waterboarding":"Water Boarding",
    "watertank":"Water Tank",
    "wax":"Wax",
    "weights":"Weights",
    "wet&messy":"Wet & Messy",
    "whipping":"Whipping",
    "white":"White Guys",
    "wrestling":"Wrestling",
    "xlhungguys":"Hung",
    "young":"Young Guys",
    "youngboys":"Young Guys",
    "youngman":"Young Guys",
}

def getGenres(genresUnformatted):
    genres = []
    for genreU in genresUnformatted:
        genreULower = genreU.lower().replace(" ","")
        if genreULower in GENRESOVERRIDE:
            genre = GENRESOVERRIDE[genreULower].strip()
        else:
            genre = genreU.strip()
        if genre and genre not in genres:
            genres.append(genre)
    return genres
